### ISSUE TITLE
Missing dependencies 

### ISSUE THREAD

**Issue by iii-james** [VahidN/iTextSharp.LGPLv2.Core#65]
# Summary of the issue
I am using iTextSharp.LGPLv2.Core in conjunction with [edge-js](https://github.com/agracio/edge-js). I ran into problems when I updated iTextSharp.LGPLv2.Core from v.1.3.1 to v1.4.1. I needed that version because I need the text rotation feature that was fixed with[ issue 21](https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/21#issuecomment-358688383). When I try to run I get the same error @mojtabakaviani had on [issue 25](https://github.com/VahidN/iTextSharp.LGPLv2.Core/issues/25). I am not sure what dotnet SDK to be on for this to go away.

## Environment

```
iTextSharp.LGPLv2.Core version: 1.4.1
.NET Core SDK version: 2.2.110
IDE: Visual Studio 2017
```

## Output:

```
Error: assembly specified in the dependencies manifest was not found -- package: 'System.Drawing.Common', version: '4.5.0-preview1-25914-04', path: 'runtimes/win/lib/netcoreapp2.0/
System.Drawing.Common.dll'
E:\Projects\DotNetCore\edge-js-quick-start-master\node_modules\edge-js\lib\edge.js:178
    return edge.initializeClrFunc(options);
                ^

TypeError: edge.initializeClrFunc is not a function
    at Object.exports.func (E:\Projects\DotNetCore\edge-js-quick-start-master\node_modules\edge-js\lib\edge.js:178:17)
    at Object.<anonymous> (E:\Projects\DotNetCore\edge-js-quick-start-master\main.js:19:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by VahidN** [comment]
Use the last version which is [v1.6.9](https://www.nuget.org/packages/iTextSharp.LGPLv2.Core/). It uses System.Drawing.Common V4.7.0.
